sudo: false
language: node_js
node_js:
  - 5
before_script:
  - npm install -g add-cors-to-couchdb && add-cors-to-couchdb
  - npm install -g gulp
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
